spring.application.name=flit-core

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/flit

keycloak.auth-server-url=http://localhost:8180
keycloak.realm=flit
keycloak.client-id=flit
keycloak.client-uuid=9bd7a15e-8b68-4b05-b6a4-11ee6fd8ad1b
keycloak.client-secret=ycckvfv0A3fC9HDMkjOWGSEnKBO4DXnu
keycloak.admin-client-id=admin-cli
keycloak.admin-client-secret=5WLCSkfZEq1m6I11852kQw5uTielGp1I