spring.application.name=flit-core

spring.datasource.url=jdbc:postgresql://localhost:5432/flit
spring.datasource.username=flit
spring.datasource.password=flit
spring.datasource.driver-class-name=org.postgresql.Driver

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/flit

keycloak.server-url=http://localhost:8180
keycloak.realm=flit
keycloak.client-id=flit
keycloak.client-secret=4ZUsyNcLY4SIuhDsTbPoielmHb33u4Er
keycloak.admin-client-id=admin-cli
keycloak.admin-client-secret=xMPXwTTo46UaMub9DWr2aVFyPmorteJS